"""Daily skill pipeline orchestration service."""

from __future__ import annotations

import json
import csv
import shutil
from pathlib import Path
from time import perf_counter
from typing import Any, Dict, Iterable, List

from configs.stock_pool import TRACKED_A_STOCKS
from core.logging import init_component_logger
from services.pipeline.steps.build_agent_input import build_snapshot_payload
from services.pipeline.steps.build_agent_input import write_agent_input_bundle
from services.pipeline.steps.build_global_context import write_global_context
from services.pipeline.steps.build_stock_research import write_stock_research_bundle
from services.pipeline.steps.refresh_data import run_refresh_data
from services.selection_system.store import load_json_file


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SKILL_FLOW_CONFIG = (
    PROJECT_ROOT
    / "configs"
    / "prompt_flow"
    / "fixed_tracked"
    / "main_policy.md"
)
SHORT_BOOK_FLOW_CONFIG = PROJECT_ROOT / "configs" / "prompt_flow" / "skill_flow_short_book.json"
LONG_BOOK_FLOW_CONFIG = PROJECT_ROOT / "configs" / "prompt_flow" / "skill_flow_long_book.json"
LOGGER = init_component_logger(
    "DailyPipeline",
    group="services/pipeline",
    filename_prefix="daily_pipeline",
)


def _round_sec(value: float) -> float:
    return round(float(value), 2)


def _slowest_stage_label(stage_costs: Dict[str, float]) -> str:
    if not stage_costs:
        return ""
    return max(stage_costs.items(), key=lambda item: item[1])[0]


def resolve_output_dir(base_dir: str, run_date: str) -> Path:
    return Path(base_dir) / "skill_runs" / run_date


def safe_clean_dir(target_dir: Path) -> None:
    if target_dir.exists():
        if target_dir.is_dir() and target_dir.parent.name == "skill_runs":
            shutil.rmtree(target_dir)
        else:
            raise ValueError(f"Refuse to clean unexpected path: {target_dir}")
    target_dir.mkdir(parents=True, exist_ok=True)


def _book_signature(book_type: str) -> str:
    return f"book-{book_type}"


def _load_selection_symbols(path: Path) -> List[str]:
    payload = load_json_file(path, default={}) or {}
    items = payload.get("items") or []
    symbols: List[str] = []
    for item in items:
        symbol = (item or {}).get("symbol")
        if isinstance(symbol, str) and symbol.strip() and symbol not in symbols:
            symbols.append(symbol.strip())
    return symbols


def _stock_name_to_code(name: str) -> str:
    """将股票中文名称转换为代码，如果已经是代码则原样返回。"""
    universe_path = PROJECT_ROOT / "data" / "universe" / "master_universe.json"
    if universe_path.exists():
        try:
            data = json.loads(universe_path.read_text(encoding="utf-8"))
            for entry in data.get("stocks", []):
                if entry.get("name") == name:
                    return entry.get("symbol", name)
        except Exception:
            pass
    return name


def _load_manual_position_symbols(base_dir: str, signature: str = "book-fixed_tracked") -> List[str]:
    override_path = (
        Path(base_dir)
        / "agent_data"
        / signature
        / "position"
        / "manual_position_override.json"
    )
    payload = load_json_file(override_path, default={}) or {}
    positions = payload.get("positions") or {}
    if not isinstance(positions, dict):
        return []

    symbols: List[str] = []
    for symbol, raw_entry in positions.items():
        if symbol == "CASH" or not isinstance(symbol, str) or not symbol.strip():
            continue
        symbol = _stock_name_to_code(symbol)
        shares = 0.0
        if isinstance(raw_entry, dict):
            raw_shares = raw_entry.get("shares")
        else:
            raw_shares = raw_entry
        try:
            shares = float(raw_shares or 0)
        except (TypeError, ValueError):
            shares = 0.0
        if shares > 0 and symbol.strip() not in symbols:
            symbols.append(symbol.strip())
    return symbols


def _dedupe_symbols(*groups: Iterable[str]) -> List[str]:
    symbols: List[str] = []
    for group in groups:
        for symbol in group:
            if isinstance(symbol, str) and symbol.strip() and symbol.strip() not in symbols:
                symbols.append(symbol.strip())
    return symbols


def _load_prefilter_symbols(path: Path) -> List[str]:
    """Read symbols from 12_quant_prefilter_*.csv generated by build-quant-prefilter."""
    if not path.exists():
        return []
    symbols: List[str] = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            symbol = (row.get("symbol") or "").strip()
            if symbol and symbol not in symbols:
                symbols.append(symbol)
    return symbols


def _collect_manifest_symbols(manifest: Dict[str, Any]) -> List[str]:
    symbols: List[str] = []
    for book in manifest.get("books") or []:
        for symbol in book.get("symbols") or []:
            if isinstance(symbol, str) and symbol and symbol not in symbols:
                symbols.append(symbol)
    return symbols


def build_run_manifest(run_date: str, *, base_dir: str = "data") -> Dict[str, Any]:
    base_path = Path(base_dir)
    selection_dir = base_path / "selection_runs" / run_date
    short_candidates = selection_dir / "08_short_book_candidates.json"
    long_candidates = selection_dir / "09_long_book_candidates.json"
    # 量化初筛产物，作为选股候选池缺失时的回退来源
    short_prefilter = selection_dir / "12_quant_prefilter_short.csv"
    long_prefilter = selection_dir / "12_quant_prefilter_long.csv"

    tracked_symbols = [entry.symbol for entry in TRACKED_A_STOCKS]
    manual_position_symbols = _load_manual_position_symbols(base_dir)
    short_symbols = _load_selection_symbols(short_candidates) if short_candidates.exists() else []
    long_symbols = _load_selection_symbols(long_candidates) if long_candidates.exists() else []

    # 选股候选池不存在时，回退到量化初筛产物
    short_source_type = "selection_candidates"
    short_source_path = str(short_candidates)
    if not short_symbols:
        short_symbols = _load_prefilter_symbols(short_prefilter)
        if short_symbols:
            short_source_type = "quant_prefilter"
            short_source_path = str(short_prefilter)
    long_source_type = "selection_candidates"
    long_source_path = str(long_candidates)
    if not long_symbols:
        long_symbols = _load_prefilter_symbols(long_prefilter)
        if long_symbols:
            long_source_type = "quant_prefilter"
            long_source_path = str(long_prefilter)
    fixed_symbols = _dedupe_symbols(tracked_symbols, manual_position_symbols, long_symbols)

    fixed_book = {
        "book_type": "fixed_tracked",
        "signature": _book_signature("fixed_tracked"),
        "prompt_config": str(SKILL_FLOW_CONFIG),
        "source_type": "unified_long_pool",
        "source_path": "configs/stock_pool.py + manual_position_override.json + long_book_candidates",
        "capital_budget": 0,
        "symbols": fixed_symbols,
        "symbol_sources": {
            "tracked_stock_pool": tracked_symbols,
            "manual_position_override": manual_position_symbols,
            "long_book_candidates": long_symbols,
            "long_book_source_type": long_source_type,
            "long_book_source_path": long_source_path,
        },
    }
    books = [
        fixed_book,
        {
            "book_type": "short_book",
            "signature": _book_signature("short_book"),
            "prompt_config": str(SHORT_BOOK_FLOW_CONFIG),
            "source_type": short_source_type,
            "source_path": short_source_path,
            "capital_budget": 200000,
            "symbols": short_symbols,
        },
        {
            "book_type": "long_book",
            "signature": _book_signature("long_book"),
            "prompt_config": str(LONG_BOOK_FLOW_CONFIG),
            "source_type": long_source_type,
            "source_path": long_source_path,
            "capital_budget": 400000,
            "symbols": long_symbols,
        },
    ]
    return {
        "run_date": run_date,
        "books": books,
        "default_books": ["fixed_tracked"],
        "all_books": ["fixed_tracked", "short_book"],
    }


def _write_manifest(output_dir: Path, manifest: Dict[str, Any]) -> Path:
    path = output_dir / "run_manifest.json"
    path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def _book_output_dir(base_output_dir: Path, book_type: str) -> Path:
    target = base_output_dir / book_type
    target.mkdir(parents=True, exist_ok=True)
    return target


def run_book_pipeline(
    run_date: str,
    *,
    output_dir: str | Path,
    symbols: Iterable[str],
    prompt_config: str | Path,
    signature: str,
    book_type: str,
    max_workers: int = 1,
) -> tuple[Path, Dict[str, Any]]:
    target_symbols = [symbol for symbol in symbols if symbol]
    target_dir = Path(output_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    stage_start = perf_counter()
    snapshot_payload = build_snapshot_payload(
        run_date,
        target_symbols,
        max_workers=max_workers,
    )
    snapshot_sec = perf_counter() - stage_start

    stage_start = perf_counter()
    write_global_context(
        run_date,
        target_dir,
    )
    global_context_sec = perf_counter() - stage_start

    stage_start = perf_counter()
    write_stock_research_bundle(
        run_date,
        target_dir,
        symbols=target_symbols,
        snapshot_payload=snapshot_payload,
        signature=signature,
        book_type=book_type,
        max_workers=max_workers,
    )
    research_sec = perf_counter() - stage_start

    stage_start = perf_counter()
    write_agent_input_bundle(
        run_date,
        target_dir,
        symbols=target_symbols,
        book_type=book_type,
        signature=signature,
        prompt_config=prompt_config,
        snapshot_payload=snapshot_payload,
    )
    agent_input_sec = perf_counter() - stage_start

    stage_costs = {
        "snapshot": snapshot_sec,
        "global_context": global_context_sec,
        "stock_research": research_sec,
        "agent_input": agent_input_sec,
    }
    metrics = {
        "book_type": book_type,
        "symbol_count": len(target_symbols),
        "max_workers": max_workers,
        "stage_costs_sec": {key: _round_sec(val) for key, val in stage_costs.items()},
        "total_sec": _round_sec(sum(stage_costs.values())),
        "slowest_stage": _slowest_stage_label(stage_costs),
    }
    return target_dir, metrics


def run_daily_pipeline_from_manifest(
    run_date: str,
    *,
    base_dir: str = "data",
    manifest: Dict[str, Any],
    refresh_data: bool = True,
    max_workers: int = 1,
    respect_default_books: bool = True,
    enabled_books: List[str] | None = None,
) -> Path:
    overall_start = perf_counter()
    output_dir = resolve_output_dir(base_dir, run_date)
    safe_clean_dir(output_dir)
    _write_manifest(output_dir, manifest)
    LOGGER.info(
        "开始执行 daily pipeline: date=%s, output_dir=%s, books=%d, max_workers=%d",
        run_date,
        output_dir,
        len(manifest.get("books") or []),
        max_workers,
    )

    refresh_sec = 0.0

    if refresh_data:
        refresh_start = perf_counter()
        run_refresh_data(
            run_date,
            signature=_book_signature("fixed_tracked"),
            symbols=_collect_manifest_symbols(manifest),
            max_workers=max_workers,
        )
        refresh_sec = perf_counter() - refresh_start
        LOGGER.info("阶段耗时 refresh_data: %.2fs", refresh_sec)

    books = manifest.get("books") or []
    if enabled_books:
        allowed_books = {
            book_type
            for book_type in enabled_books
            if isinstance(book_type, str) and book_type
        }
        books = [
            book
            for book in books
            if isinstance(book, dict) and book.get("book_type") in allowed_books
        ]
    default_books = manifest.get("default_books")
    if not enabled_books and respect_default_books and isinstance(default_books, list) and default_books:
        allowed_books = {
            book_type
            for book_type in default_books
            if isinstance(book_type, str) and book_type
        }
        books = [
            book
            for book in books
            if isinstance(book, dict) and book.get("book_type") in allowed_books
        ]
    book_metrics: List[Dict[str, Any]] = []
    for book in books:
        symbols = book.get("symbols") or []
        if not symbols:
            LOGGER.info(
                "跳过空账本: book_type=%s, source=%s",
                book.get("book_type"),
                book.get("source_path"),
            )
            continue
        book_start = perf_counter()
        _, metrics = run_book_pipeline(
            run_date,
            output_dir=_book_output_dir(output_dir, book["book_type"]),
            symbols=symbols,
            prompt_config=book["prompt_config"],
            signature=book["signature"],
            book_type=book["book_type"],
            max_workers=max_workers,
        )
        measured_book_sec = perf_counter() - book_start
        metrics["measured_total_sec"] = _round_sec(measured_book_sec)
        book_metrics.append(metrics)
        LOGGER.info(
            "账本耗时 book_type=%s symbols=%d total=%.2fs slowest=%s breakdown=%s",
            metrics["book_type"],
            metrics["symbol_count"],
            measured_book_sec,
            metrics["slowest_stage"],
            json.dumps(metrics["stage_costs_sec"], ensure_ascii=False, sort_keys=True),
        )

    overall_sec = perf_counter() - overall_start
    stage_totals: Dict[str, float] = {"refresh_data": refresh_sec}
    for metrics in book_metrics:
        stage_totals[metrics["book_type"]] = float(metrics.get("measured_total_sec") or 0.0)
    slowest_top_level = _slowest_stage_label(stage_totals)
    LOGGER.info(
        "daily pipeline 完成: date=%s total=%.2fs slowest_top_level=%s stage_totals=%s",
        run_date,
        overall_sec,
        slowest_top_level,
        json.dumps({key: _round_sec(val) for key, val in stage_totals.items()}, ensure_ascii=False, sort_keys=True),
    )
    return output_dir


def run_daily_pipeline(
    run_date: str,
    *,
    base_dir: str = "data",
    prompt_config: str | Path | None = None,
    signature: str = "",
    manifest_path: str | Path | None = None,
    max_workers: int = 4,
    skip_disclosures: bool = False,
    all_books: bool = False,
) -> Path:
    LOGGER.info(
        "run_daily_pipeline 请求: date=%s, base_dir=%s, manifest=%s, prompt_config=%s, signature=%s, max_workers=%d",
        run_date,
        base_dir,
        manifest_path or "auto",
        str(prompt_config) if prompt_config else "",
        signature,
        max_workers,
    )
    if manifest_path and str(manifest_path) != "auto":
        manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    else:
        manifest = build_run_manifest(run_date, base_dir=base_dir)
    if prompt_config or signature:
        # 默认日常调用：只跑 fixed_tracked 单账本。
        # 只有显式传入 manifest 且不再提供 prompt_config 时，才进入三账本模式。
        fixed_book = next(
            (book for book in manifest.get("books", []) if book.get("book_type") == "fixed_tracked"),
            {},
        )
        fixed_symbols = list(fixed_book.get("symbols") or [])
        output_dir = resolve_output_dir(base_dir, run_date)
        safe_clean_dir(output_dir)
        _write_manifest(output_dir, manifest)
        overall_start = perf_counter()
        refresh_start = perf_counter()
        run_refresh_data(
            run_date,
            signature=signature or _book_signature("fixed_tracked"),
            symbols=fixed_symbols,
            max_workers=max_workers,
            skip_disclosures=skip_disclosures,
        )
        refresh_sec = perf_counter() - refresh_start
        LOGGER.info("阶段耗时 refresh_data: %.2fs", refresh_sec)
        _, metrics = run_book_pipeline(
            run_date,
            output_dir=_book_output_dir(output_dir, "fixed_tracked"),
            symbols=fixed_symbols,
            prompt_config=prompt_config or SKILL_FLOW_CONFIG,
            signature=signature or _book_signature("fixed_tracked"),
            book_type="fixed_tracked",
            max_workers=max_workers,
        )
        overall_sec = perf_counter() - overall_start
        LOGGER.info(
            "账本耗时 book_type=%s symbols=%d total=%.2fs slowest=%s breakdown=%s",
            metrics["book_type"],
            metrics["symbol_count"],
            float(metrics["total_sec"]),
            metrics["slowest_stage"],
            json.dumps(metrics["stage_costs_sec"], ensure_ascii=False, sort_keys=True),
        )
        LOGGER.info(
            "daily pipeline 完成(兼容单账本模式): date=%s total=%.2fs slowest_top_level=%s stage_totals=%s",
            run_date,
            overall_sec,
            _slowest_stage_label({"refresh_data": refresh_sec, "fixed_tracked": float(metrics["total_sec"])}),
            json.dumps(
                {"refresh_data": _round_sec(refresh_sec), "fixed_tracked": float(metrics["total_sec"])},
                ensure_ascii=False,
                sort_keys=True,
            ),
        )
        return output_dir
    return run_daily_pipeline_from_manifest(
        run_date,
        base_dir=base_dir,
        manifest=manifest,
        max_workers=max_workers,
        respect_default_books=not all_books,
        enabled_books=manifest.get("all_books") if all_books else None,
    )
